### ISSUE TITLE
Make it possible to upload challenge files

### ISSUE THREAD

**Issue by Gitoffomalawn** [mitre-cyber-academy/ctf-scoreboard#152] opened 2018-07-12 07:54 UTC
Currently, it's only possible to make challenges without providing the users with a file (such as a text file, or a pcap). This makes certain challenges difficult to implement without a dedicated secondary infrastructure.

Features that would solve this issue would be:
- Possibility for admin to upload files.
- Possibility for users to download files.

**Comment by rbclark** [comment] 2018-07-12 12:48
Agreed that this would be a useful feature for us to have. The biggest issue is we normally use Heroku for deployment which does not provide any sort of permanent back-end storage. This means whatever file upload we end up using here should have the option of pointing at multiple back-ends, including S3 which is what we normally use.

**Comment by Bialogs** [comment] 2019-02-25 05:26
I think we can wrap this up as a duplicate of #89 and make sure to use activestorage so people aren't forced into s3...

**Closed by Bialogs** 2019-02-25 05:26 UTC
Labels: enhancement
