### ISSUE TITLE
Additional questions on user edit page

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#115] opened 2017-09-20 19:03 UTC
After the competition we should have some additional fields show up on the users page. Some important questions we should add include:

1. Include field for resume upload
2. Include field for unofficial transcript
3. Include field for uploading photo release form
4. Include question asking if the player is interested in a summer internship (mention that internships run end of May through August)
5. Willing to travel to MITRE location for internship?
6. Ask for T-Shirt size in case we are able to send out T-Shirts that year.
7. Add "Interested in Internship" question for users. (should only show this when the user states they are Eligible).

**Comment by Bialogs** [comment] 2018-01-09 15:24
Duplicate of #16

**Closed by Bialogs** 2018-01-09 15:24 UTC
Labels: enhancement
