### ISSUE TITLE
Add optional support for resume and transcript collection

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#131] opened 2017-11-30 20:30 UTC
We currently have to email all of the top 10 team members individually and ask them to send us their  resumes and transcripts. This should be handled automatically by the scoreboard. Resumes should be an optional field for all users and should include a description stating that "Resumes will be used for consideration into the MITRE internship program". We also need to automatically email the top 10 teams from each category after the competition and request again that they submit resumes as part of the congratulations email. Another email a week or two later to anyone in the top 10 who has not yet submitted one is not a bad idea either.

**Comment by Bialogs** [comment] 2018-01-09 15:23
Duplicate of #16

**Closed by Bialogs** 2018-01-09 15:23 UTC
Labels: enhancement
